scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Adrenal/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Adrenal/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Cerebrum/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Cerebrum/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Eye/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Eye/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Heart/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Heart/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Intestine/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Intestine/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Kidney/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Kidney/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Liver/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Liver/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Lung/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Lung/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Muscle/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Muscle/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Placenta/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Placenta/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Stomach/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Stomach/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE149683_Thymus/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE149683_Thymus/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE166547/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE166547/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE174367_scATAC_Ref/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE174367_scATAC_Ref/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE151302/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE151302/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5057721/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5057721/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5057724/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5057724/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSE165906/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSE165906/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5057811/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5057811/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5057812/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5057812/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5057816/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5057816/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5292858/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5292858/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5292863/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5292863/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5292866/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5292866/chunk/
scp /public/home/lcq/rgzn/yuzhengmin/keti/database/sc_variant/table/trs/GSM5292875/chunk/* root@bio.liclab.net:/mnt/data3/workspace/SCVdb/data/data/trs/GSM5292875/chunk/
